name: Build and Push Docker Image

# Trigger the workflow on every push to the main branch
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
      - "docker/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image from the docker/nginx/Dockerfile
      - name: Build Docker image
        run: |
          docker build -t christianfehlinger/nginx:latest docker/nginx

      # Push the image to Docker Hub (optional)
      - name: Push Docker image
        run: |
          docker push christianfehlinger/nginx:latest
