name: Build and Push Docker Image

# Trigger the workflow on every push to the main branch
on:
  push:
    branches:
    - main
    paths:
      - "docker/**"

# Schedule the workflow to run every Monday at 5:00 AM
  schedule:
    - cron: '0 5 * * 1'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image from the docker/nginx/Dockerfile
      - name: Build Docker image
        id: build
        run: |
          DOCKERTAG=$(date +%Y%m%d%H%M%S)
          docker build -t christianfehlinger/nginx:$DOCKERTAG -t christianfehlinger/nginx:latest docker/nginx
          echo "DOCKERTAG=$DOCKERTAG" >> "$GITHUB_ENV"

      - name: Push Docker image
        run: |
          docker push christianfehlinger/nginx:latest
          docker push christianfehlinger/nginx:${{ env.DOCKERTAG }}
